In [3]:
import numpy as np

In [546]:
def schmidt(vec1, vec2):
    normal_vec1 = vec1 / np.linalg.norm(vec1)
    orth_vec2 = vec2 - np.dot(vec2, normal_vec1) / np.dot(normal_vec1, normal_vec1) * normal_vec1
    normal_vec2 = orth_vec2 / np.linalg.norm(orth_vec2)
    return normal_vec1, normal_vec2
def same(x1, x2, delta=1e-5):
    return np.linalg.norm(x1 - x2) < delta

In [568]:
v1 = np.random.rand(3)
v2 = np.random.rand(3)
n1, n2 = schmidt(v1, v2)
np.dot(n1, n2)
same(1, 1.1)

False

In [615]:
def power_iter(A, b_k0, num_iter = 100, delta = 1e-6):
    b_k = np.copy(b_k0)
    for i in range(num_iter):
        y = np.matmul(A, b_k)
        b_k1 = y / np.linalg.norm(y)
        if (np.linalg.norm(b_k1 - b_k) < delta ) or (np.linalg.norm(b_k1 + b_k)) < delta:
            break;
        b_k = b_k1
        lambda_k = np.dot(b_k1, np.dot(A, b_k1)) / np.dot(b_k1, b_k1)
        print("the {0}th iter, lambda:{1}, enginvector:{2}".format(i, lambda_k, b_k1))
    lambda_k = np.matmul(b_k1, np.dot(A, b_k1))
    return lambda_k, b_k1

def get_all_lambda(A, num_iter = 100, delta = 1e-6):
    lambda_lst = []
    evec_list = []
    neg_flag = False
    for i in range(A.shape[0]):
        if neg_flag:
            neg_flag = False
            continue
        b_k0 = np.random.rand(A.shape[1])
        b_k1 = np.random.rand(A.shape[1])
        lambda_, evec = power_iter(A, b_k0, num_iter, delta)
        lambda2, evec2 = power_iter(A, b_k1, num_iter, delta)
        if (np.abs(lambda_ - lambda2) > 1e-3):
            neg_flag = True
            lambda_sqrt, evec_added = power_iter(np.matmul(A, A), b_k0, num_iter, delta)
            lambda_sqrt, evec_minus = power_iter(np.matmul(A, A), np.matmul(A, b_k0), num_iter, delta)
            evec = evec_added + evec_minus
            evec2 = evec_added - evec_minus
            # lambda_ = np.sqrt(lambda_sqrt)
            lambda_ = np.matmul(evec, np.matmul(A, evec)) / np.dot(evec, evec)
            # assert(same(np.matmul(A, evec), lambda_ * evec))
            lambda2 = -lambda_
            evec, evec2 = schmidt(evec, evec2)

        lambda_lst.append(lambda_)
        evec_list.append(evec)
        A = A - lambda_ * np.outer(evec, evec)
        #append next lambda2 and evec2 if lambda1 = - lambda2
        if (neg_flag):
            A = A - lambda2 * np.outer(evec2, evec2)
            lambda_lst.append(lambda2)
            evec_list.append(evec2)
            
    print("特征值， 特征向量")
    for i in range(len(lambda_lst)):
        print(lambda_lst[i], evec_list[i])

In [616]:
A = np.array([[8, 0, 0, 0], [0, -8, 0, 0], [0, 0, 8, 0],[0, 0, 0, 1]])


In [617]:
# A = 10 * np.random.rand(4, 4)
get_all_lambda(A, delta=1e-10)
np.linalg.eig(A)


the 0th iter, lambda:6.708393736560959, enginvector:[ 0.72983447 -0.28345473  0.62139297  0.02942522]
the 1th iter, lambda:6.713263234964148, enginvector:[0.73014569 0.28357561 0.62165795 0.00367972]
the 2th iter, lambda:6.7133393867961715, enginvector:[ 7.30150555e-01 -2.83577495e-01  6.21662094e-01  4.59968177e-04]
the 3th iter, lambda:6.713340576684656, enginvector:[7.30150631e-01 2.83577525e-01 6.21662159e-01 5.74960281e-05]
the 4th iter, lambda:6.713340595276667, enginvector:[ 7.30150632e-01 -2.83577525e-01  6.21662160e-01  7.18700353e-06]
the 5th iter, lambda:6.713340595567168, enginvector:[7.30150632e-01 2.83577525e-01 6.21662160e-01 8.98375441e-07]
the 6th iter, lambda:6.713340595571706, enginvector:[ 7.30150632e-01 -2.83577525e-01  6.21662160e-01  1.12296930e-07]
the 7th iter, lambda:6.7133405955717755, enginvector:[7.30150632e-01 2.83577525e-01 6.21662160e-01 1.40371163e-08]
the 8th iter, lambda:6.713340595571777, enginvector:[ 7.30150632e-01 -2.83577525e-01  6.21662160e-01  

(array([ 8., -8.,  8.,  1.]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

In [530]:
evec1 = np.array([8.79762837e-01, 4.75412822e-01, 9.33935517e-07, 1.34632714e-43])
lambda1 = 8
evec2 = np.array([4.75412822e-01, -8.79762837e-01, -1.14077483e-06, 1.23428451e-39])
lambda2 = -8
print(np.matmul(A, evec1), lambda2 * evec1)


[ 7.03810270e+00 -3.80330258e+00  5.60361310e-06  1.34632714e-43] [-7.03810270e+00 -3.80330258e+00 -7.47148414e-06 -1.07706171e-42]


In [525]:

print(np.linalg.eig(A))
print(np.linalg.eig(np.matmul(A, A)))

(array([ 8., -8.,  6.,  1.]), array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]))
(array([64., 64., 36.,  1.]), array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]))
