In [20]:
import numpy as np

In [21]:
def schmidt(vec1, vec2):
    normal_vec1 = vec1 / np.linalg.norm(vec1)
    orth_vec2 = vec2 - np.dot(vec2, normal_vec1) / np.dot(normal_vec1, normal_vec1) * normal_vec1
    normal_vec2 = orth_vec2 / np.linalg.norm(orth_vec2)
    return normal_vec1, normal_vec2
def same(x1, x2, delta=1e-5):
    return np.linalg.norm(x1 - x2) < delta

In [22]:
v1 = np.random.rand(3)
v2 = np.random.rand(3)
n1, n2 = schmidt(v1, v2)
np.dot(n1, n2)
same(1, 1.1)

False

In [23]:
def power_iter(A, b_k0, num_iter = 100, delta = 1e-6, isPrint=True):
    b_k = np.copy(b_k0)
    for i in range(num_iter):
        y = np.matmul(A, b_k)
        b_k1 = y / np.linalg.norm(y)
        if (np.linalg.norm(b_k1 - b_k) < delta ) or (np.linalg.norm(b_k1 + b_k)) < delta:
            break;
        b_k = b_k1
        lambda_k = np.dot(b_k1, np.dot(A, b_k1)) / np.dot(b_k1, b_k1)
        if isPrint:
            print("the {0}th iter, lambda:{1}, enginvector:{2}".format(i, lambda_k, b_k1))
    
    lambda_k = np.matmul(b_k1, np.dot(A, b_k1))
    return lambda_k, b_k1

def get_all_lambda(A, num_iter = 100, delta = 1e-6):
    lambda_lst = []
    evec_list = []
    neg_flag = False
    for i in range(A.shape[0]):
        if neg_flag:
            neg_flag = False
            continue
        b_k0 = np.random.rand(A.shape[1])
        b_k1 = np.random.rand(A.shape[1])
        print("正在计算第{0} 个特征向量".format(i))
        lambda_, evec = power_iter(A, b_k0, num_iter, delta)
        lambda2, evec2 = power_iter(A, b_k1, num_iter, delta, isPrint=False)
        if (np.abs(lambda_ - lambda2) > 1e-2):
            neg_flag = True
            print("检测到互反的特征值,正在计算第{0}和{1} 个特征向量".format(i, i+1))
            print("计算特征向量之和 :")
            lambda_sqrt, evec_added = power_iter(np.matmul(A, A), b_k0, num_iter, delta)
            print("计算特征向量之差 :")
            lambda_sqrt, evec_minus = power_iter(np.matmul(A, A), np.matmul(A, b_k0), num_iter, delta)
            evec = evec_added + evec_minus
            evec2 = evec_added - evec_minus
            # lambda_ = np.sqrt(lambda_sqrt)
            lambda_ = np.matmul(evec, np.matmul(A, evec)) / np.dot(evec, evec)
            # assert(same(np.matmul(A, evec), lambda_ * evec))
            lambda2 = -lambda_
            evec, evec2 = schmidt(evec, evec2)

        lambda_lst.append(lambda_)
        evec_list.append(evec)
        A = A - lambda_ * np.outer(evec, evec)
        #append next lambda2 and evec2 if lambda1 = - lambda2
        if (neg_flag):
            A = A - lambda2 * np.outer(evec2, evec2)
            lambda_lst.append(lambda2)
            evec_list.append(evec2)
            
    print("特征值， 特征向量")
    for i in range(len(lambda_lst)):
        print(lambda_lst[i], evec_list[i])

In [24]:
A = np.array([[3, 0, 0],
              [0, 2, 0],
              [0, 0, 1]])
get_all_lambda(A, delta=1e-10)
np.linalg.eig(A)


正在计算第0 个特征向量
the 0th iter, lambda:2.7573411090733067, enginvector:[0.87419636 0.47843763 0.08293469]
the 1th iter, lambda:2.88085749215526, enginvector:[0.93900972 0.34260616 0.0296945 ]
the 2th iter, lambda:2.943935689752363, enginvector:[0.97161751 0.2363356  0.01024189]
the 3th iter, lambda:2.974354274146133, enginvector:[0.98709995 0.16006769 0.00346836]
the 4th iter, lambda:2.988445323501629, enginvector:[0.99420656 0.10748007 0.00116444]
the 5th iter, lambda:2.9948323210349086, enginvector:[9.97412890e-01 7.18844608e-02 3.89399977e-04]
the 6th iter, lambda:2.9976967424616134, enginvector:[9.98847716e-01 4.79919133e-02 1.29986716e-04]
the 7th iter, lambda:2.9989750297119615, enginvector:[9.99487384e-01 3.20150984e-02 4.33566534e-05]
the 8th iter, lambda:2.9995441993575316, enginvector:[9.99772074e-01 2.13494783e-02 1.44563343e-05]
the 9th iter, lambda:2.9997973707657164, enginvector:[9.99898680e-01 1.42347879e-02 4.81938833e-06]
the 10th iter, lambda:2.999909932438958, enginvector

(array([3., 2., 1.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [25]:

B = np.array([[2, 0, 0],
              [0, 2, 0],
              [0, 0, 1]])
get_all_lambda(B, delta=1e-10)
np.linalg.eig(B)

正在计算第0 个特征向量
the 0th iter, lambda:1.893409044135298, enginvector:[0.77679117 0.53852067 0.3264827 ]
the 1th iter, lambda:1.9710368539685703, enginvector:[0.80983579 0.56142929 0.17018562]
the 2th iter, lambda:1.992598434014774, enginvector:[0.81877751 0.56762825 0.08603235]
the 3th iter, lambda:1.9981392793185153, enginvector:[0.8210596  0.56921034 0.04313607]
the 4th iter, lambda:1.999534169744636, enginvector:[0.82163311 0.56960794 0.0215831 ]
the 5th iter, lambda:1.9998835017348466, enginvector:[0.82177668 0.56970746 0.01079344]
the 6th iter, lambda:1.9999708728887682, enginvector:[0.82181258 0.56973235 0.00539695]
the 7th iter, lambda:1.9999927180631158, enginvector:[0.82182156 0.56973858 0.00269851]
the 8th iter, lambda:1.9999981795058364, enginvector:[0.8218238  0.56974013 0.00134926]
the 9th iter, lambda:1.9999995448758376, enginvector:[8.21824362e-01 5.69740523e-01 6.74628907e-04]
the 10th iter, lambda:1.9999998862189206, enginvector:[8.21824502e-01 5.69740620e-01 3.37314511e-0

(array([2., 2., 1.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [26]:

C = np.array([[-2, 0, 0],
              [0, 2, 0],
              [0, 0, 1]])
get_all_lambda(C, delta=1e-10)
np.linalg.eig(C)

正在计算第0 个特征向量
the 0th iter, lambda:0.7110287660129587, enginvector:[-0.55568985  0.79837485  0.23196203]
the 1th iter, lambda:0.6988770120541907, enginvector:[0.56725341 0.81498853 0.11839451]
the 2th iter, lambda:0.6956776885419692, enginvector:[-0.57025888  0.81930657  0.0595109 ]
the 3th iter, lambda:0.694867206979502, enginvector:[0.57101774 0.82039685 0.02979504]
the 4th iter, lambda:0.6946639116075557, enginvector:[-0.57120793  0.8206701   0.01490248]
the 5th iter, lambda:0.6946130454306513, enginvector:[0.57125551 0.82073846 0.00745186]
the 6th iter, lambda:0.6946003262382409, enginvector:[-0.5712674   0.82075555  0.00372601]
the 7th iter, lambda:0.6945971462745906, enginvector:[0.57127038 0.82075982 0.00186301]
the 8th iter, lambda:0.6945963512733306, enginvector:[-0.57127112  0.82076089  0.00093151]
the 9th iter, lambda:0.6945961525223688, enginvector:[5.71271308e-01 8.20761156e-01 4.65754309e-04]
the 10th iter, lambda:0.6945961028345883, enginvector:[-5.71271355e-01  8.2076122

(array([-2.,  2.,  1.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))