In [3]:
import numpy as np

In [546]:
def schmidt(vec1, vec2):
    normal_vec1 = vec1 / np.linalg.norm(vec1)
    orth_vec2 = vec2 - np.dot(vec2, normal_vec1) / np.dot(normal_vec1, normal_vec1) * normal_vec1
    normal_vec2 = orth_vec2 / np.linalg.norm(orth_vec2)
    return normal_vec1, normal_vec2
def same(x1, x2, delta=1e-5):
    return np.linalg.norm(x1 - x2) < delta

def get_eigenvector_of_lambda(A, lambda_):
    null_space = np.linalg.svd(A)[2].T[:, 3:]

In [519]:
v1 = np.random.rand(3)
v2 = np.random.rand(3)
n1, n2 = schmidt(v1, v2)
np.dot(n1, n2)
same(1, 1.1)

False

In [531]:
def power_iter(A, num_iter = 100, delta = 1e-6):
    b_k = np.random.rand(A.shape[0])
    for i in range(num_iter):
        y = np.matmul(A, b_k)
        b_k1 = y / np.linalg.norm(y)
        if (np.linalg.norm(b_k1 - b_k) < delta ) or (np.linalg.norm(b_k1 + b_k)) < delta:
            break;
        b_k = b_k1
        lambda_k = np.dot(b_k1, np.dot(A, b_k1)) / np.dot(b_k1, b_k1)
        print("the {0}th iter, lambda:{1}, enginvector:{2}".format(i, lambda_k, b_k1))
    lambda_k = np.matmul(b_k1, np.dot(A, b_k1))
    return lambda_k, b_k1

def get_all_lambda(A, num_iter = 100, delta = 1e-6):
    lambda_lst = []
    evec_list = []
    neg_flag = False
    for i in range(A.shape[0]):
        if neg_flag:
            neg_flag = False
            continue

        lambda_, evec = power_iter(A, num_iter, delta)
        lambda2, evec2 = power_iter(A, num_iter, delta)
        if (np.abs(lambda_ - lambda2) > delta):
            neg_flag = True
            lambda_, evec = power_iter(np.matmul(A, A), num_iter, delta)
            # lambda2, evec2 = power_iter(np.matmul(A, A), num_iter, delta)
            lambda_ = np.sqrt(lambda_)
            lambda2 = - lambda_

            evec, evec2 = schmidt(evec, evec2)

        lambda_lst.append(lambda_)
        evec_list.append(evec)
        A = A - lambda_ * np.outer(evec, evec)
        #append next lambda2 and evec2 if lambda1 = - lambda2
        if (neg_flag):
            A = A - lambda2 * np.outer(evec2, evec2)
            lambda_lst.append(lambda2)
            evec_list.append(evec2)
            
    print("特征值， 特征向量")
    for i in range(len(lambda_lst)):
        print(lambda_lst[i], evec_list[i])

In [566]:
A = np.array([[8, 0, 0, 0], [0, -8, 0, 0], [0, 0, 6, 0],[0, 0, 0, 1]])
lambda_, evec = power_iter(A, 1000, 1e-10)
A2 = np.matmul(A, A)
lambda1, evec1 = power_iter(A2, 1000, 1e-10)
print(lambda_, evec)
print(lambda1, evec1)
print(same(np.matmul(A, evec), lambda_ * evec))
print(same(np.matmul(A, evec1), -8* evec1))

the 0th iter, lambda:2.507381932677435, enginvector:[ 0.76478728 -0.57063296  0.26217649  0.14402059]
the 1th iter, lambda:2.429180204959323, enginvector:[0.78485766 0.58560812 0.20179261 0.01847502]
the 2th iter, lambda:2.364878699341287, enginvector:[ 0.79207913 -0.5909963   0.15273698  0.00233063]
the 3th iter, lambda:2.3274023260662053, enginvector:[7.96154570e-01 5.94037123e-01 1.15142135e-01 2.92827156e-04]
the 4th iter, lambda:2.30597617963619, enginvector:[ 7.98473645e-01 -5.95767460e-01  8.66081444e-02  3.67100145e-05]
the 5th iter, lambda:2.293813683596408, enginvector:[7.99787044e-01 5.96747431e-01 6.50629538e-02 4.59629980e-06]
the 6th iter, lambda:2.286937017719552, enginvector:[ 8.00528685e-01 -5.97300794e-01  4.88424649e-02  5.75070242e-07]
the 7th iter, lambda:2.283057667158822, enginvector:[8.00946766e-01 5.97612737e-01 3.66509799e-02 7.19213220e-08]
the 8th iter, lambda:2.280871968091477, enginvector:[ 8.01182224e-01 -5.97788421e-01  2.74963158e-02  8.99280813e-09]
th

In [551]:
# A = 10 * np.random.rand(4, 4)
get_all_lambda(A, delta=1e-10)
np.linalg.eig(A)


the 0th iter, lambda:-0.7466386216069267, enginvector:[ 0.66955862 -0.73841825  0.06716207  0.04380634]
the 1th iter, lambda:-0.7633166169154182, enginvector:[0.67085545 0.73984845 0.05046912 0.0054864 ]
the 2th iter, lambda:-0.7709143943898162, enginvector:[ 6.71239513e-01 -7.40272006e-01  3.78735075e-02  6.86192368e-04]
the 3th iter, lambda:-0.7751669808457005, enginvector:[6.71450386e-01 7.40504567e-01 2.84140543e-02 8.58009924e-05]
the 4th iter, lambda:-0.7775609593004673, enginvector:[ 6.71569005e-01 -7.40635384e-01  2.13143054e-02  1.07270188e-05]
the 5th iter, lambda:-0.7789083087557516, enginvector:[6.71635754e-01 7.40708998e-01 1.59873179e-02 1.34101062e-06]
the 6th iter, lambda:-0.7796664281530544, enginvector:[ 6.71673309e-01 -7.40750416e-01  1.19911589e-02  1.67635700e-07]
the 7th iter, lambda:-0.7800929448344577, enginvector:[6.71694436e-01 7.40773716e-01 8.99365207e-03 2.09551217e-08]
the 8th iter, lambda:-0.780332884051947, enginvector:[ 6.71706322e-01 -7.40786823e-01  6

(array([ 8., -8.,  6.,  1.]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

In [530]:
evec1 = np.array([8.79762837e-01, 4.75412822e-01, 9.33935517e-07, 1.34632714e-43])
lambda1 = 8
evec2 = np.array([4.75412822e-01, -8.79762837e-01, -1.14077483e-06, 1.23428451e-39])
lambda2 = -8
print(np.matmul(A, evec1), lambda2 * evec1)


[ 7.03810270e+00 -3.80330258e+00  5.60361310e-06  1.34632714e-43] [-7.03810270e+00 -3.80330258e+00 -7.47148414e-06 -1.07706171e-42]


In [525]:

print(np.linalg.eig(A))
print(np.linalg.eig(np.matmul(A, A)))

(array([ 8., -8.,  6.,  1.]), array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]))
(array([64., 64., 36.,  1.]), array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]))
